# Build for Markturn
version: 2.1

jobs:
  build:
    docker:
      - image: drudy/markturn_ubuntu20.04
    steps:
      - checkout
      - run: apt update
      - run: mkdir build
      - run: cd build && cmake -DLINK_STATIC=OFF -DCMAKE_BUILD_TYPE=Release .. -G Ninja
      - run: cd build && ninja && ninja install && ldconfig
      - run: cd build && ctest && cpack -G DEB
      - store_artifacts:
          path: build/markturn-1.0.0-Linux.deb
      - store_test_results:
          path: test-results
